### ISSUE TITLE
Export seems broken

### ISSUE THREAD

**Issue by davidhoare** [stephomi/sculptgl#43]
Thank you for a tremendous application!

In the last couple days, exporting .stl and other export types seems broken. giving this error in Chrome and Firefox is giving this error:
```
sculptgl.js:11 Uncaught TypeError: Yr is not a functionsaveFileAsSTL @ sculptgl.js:11_
onClick @ sculptgl.js:10
```

**Comment by stephomi** [comment]
Thanks for the report!
Indeed I broke it recently, just fixed it with ee1bdf98e9b51f55375a9dbee295e97b9a983bc6.
The fix should be live.
